export const TABS = [
  "What's new",
  'Column',
  '신학특강 요약과 Review',
  '게시판',
];

export const PROGRAMS = [
  { title: '비전스쿨', isRecruiting: true },
  { title: '해외 비전스쿨', isRecruiting: false },
  { title: '영어 비전스쿨', isRecruiting: false },
  { title: 'M&M스쿨', isRecruiting: false },
  { title: 'M&B스쿨', isRecruiting: false },
];

export const MAIN_MENU_DATA = [
  {
    title: 'INTERCP 소개',
    path: 'introduction',
    subMenuNames: [
      '개요',
      '사역정신',
      '신앙고백',
      '신학 매뉴얼',
      '선교정책',
      '사명선언문',
      '훈련원, 산하단체, 연구실',
      '선교운동',
      '선교사 파송절차',
      '사역개념도',
      '선교훈련과정',
      '국내외 지부현황',
      '인터콥 캠퍼스',
      '정기집회안내',
      '사역에 동역하려면',
    ],
  },
  {
    title: '국내훈련프로그램',
    path: 'internal',
    subMenuNames: [
      '비전스쿨',
      '해외비전스쿨',
      '영어비전스쿨',
      '여성비전스쿨',
      '직장여성비전스쿨',
      '시니어비전스쿨',
      '청소년비전스쿨',
      '청사에듀스쿨',
      '부모비전스쿨',
      '어린이비전스쿨',
      '키즈비전스쿨',
      'BTJ스쿨',
      'MnB스쿨',
      'MnM스쿨',
      'MK샘스쿨',
      '목회자비전스쿨',
      'ADS(예배기도사역자훈련)',
      '비전스쿨 강의내용',
    ],
  },
  {
    title: '전문사역분야',
    path: 'ministryPart',
    subMenuNames: [
      '개요',
      '사역정신',
      '신앙고백',
      '신학 매뉴얼',
      '선교정책',
      '사명선언문',
      '훈련원, 산하단체, 연구실',
      '선교운동',
      '선교사 파송절차',
      '사역개념도',
      '선교훈련과정',
      '국내외 지부현황',
      '인터콥 캠퍼스',
      '정기집회안내',
      '사역에 동역하려면',
    ],
  },
  {
    title: '해외프로그램',
    path: 'overseas',
    subMenuNames: ['개요', '의료분야', 'IT분야', '스포츠분야', '과학기술분야'],
  },
  {
    title: '지역연구',
    path: 'regionalStudy',
    subMenuNames: null,
  },
  {
    title: '게시판',
    path: 'board',
    subMenuNames: null,
  },
];
